FROM rabbitmq:3.6.11-management
MAINTAINER Will Liu "william.q.liu@gmail.com"
RUN apt-get update && apt-get -y upgrade

# Expose ports.
EXPOSE 5672
EXPOSE 15672

# Define default command.
#CMD ["rabbitmq-start"]
#CM ["rabbitmq-server"]
